### ISSUE TITLE
Why cigar10 did not achieve Non-iid in sampling.py ？

### ISSUE THREAD

**Issue by Murphyzzz** [shaoxiongji/federated-learning#10]
Is it impossible to achieve or other reasons ？

**Comment by Murphyzzz** [comment]
First of all, thank u for your code ,it is really nice !

**Comment by shaoxiongji** [comment]
> Is it impossible to achieve or other reasons ？
It is possible, but no plan atm as I failed to achieve reported results with iid partitioning.
