### ISSUE TITLE
并行

### ISSUE THREAD

**Issue by Ray-1997** [shaoxiongji/federated-learning#14]
你好，请问代码有实现CPU并行训练吗？还是只能每轮将每个worker都训练一遍然后收集参数这样来模拟联邦学习

**Comment by shaoxiongji** [comment]
你好，我暂时没有CPU并行的计划，欢迎PR

**Comment by chaoyanghe** [comment]
@Ray-1997 FedML支持并行，还包括mobile端以及单机模拟：https://fedml.ai
