### ISSUE TITLE
issues of running python main_fed.py --dataset mnist --num_channels 1 --model cnn --epochs 50 --gpu 0

### ISSUE THREAD

**Issue by allensun217** [shaoxiongji/federated-learning#2]
when I tried to run python main_fed.py --dataset mnist --num_channels 1 --model cnn --epochs 50 --gpu 0, then it shows me a problem.

Jians-Air:FedAvg jiansun$ python main_fed.py --dataset mnist --num_channels 1 --model cnn --epochs 50 --gpu 0
Traceback (most recent call last):
  File "main_fed.py", line 11, in <module>
    from torchvision import datasets, transforms
  File "/Library/Python/2.7/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models

￼

**Comment by shaoxiongji** [comment]
Sorry, I can't understand what's your problem. Did you install torchvision?
